- src/server/controllers/payment.controller.js
- src/server/routes.js
- src/server/services/cpms.service.js
- src/server/services/payment.service.js
- test/controllers/payment.controller.spec.js
- test/services/cpms.service.spec.js
* Very similar to `rsp-public-portal`
* Check for `801` code in response payload indicating the payment was successful
* Call payment service to record the payment when successful and return to unimplemented receipt page
* Render the failed payment page if anything goes wrong
> Add CPMS post card payment confirmation logic

- package-lock.json
- src/server/controllers/payment.controller.js
- src/server/routes.js
- src/server/services/cpms.service.js
- src/server/views/layouts/partials/header.njk
- src/server/views/payment/groupCash.njk
- src/server/views/payment/groupCheque.njk
- src/server/views/payment/groupPostalOrder.njk
- src/server/views/payment/multiPaymentReceipt.njk
- src/server/views/payment/penaltyGroupTypeBreakdown.njk
- src/server/views/penalty/penaltyGroupSummary.njk
- test/controllers/payment.controller.spec.js
- test/services/cpms.service.spec.js
* Add Nunjucks templates for cash/cheque/postal payments based on single penalty payment forms
* Create payload specific for the payment type and submit to CPMS orchestration on unified `groupPayment` endpoint
* Call payment service to produce a group payment record with the specific payment type
> Add templates and payment endpoints for penalty group non-card payment

- src/public/scss/styles.scss
- src/server/controllers/main.controller.js
- src/server/controllers/payment.controller.js
- src/server/services/cpms.service.js
- src/server/services/penalty.service.js
- src/server/services/penaltyGroup.service.js
- src/server/views/layouts/partials/body-scripts.njk
- src/server/views/layouts/partials/head.njk
- src/server/views/layouts/partials/header.njk
- src/server/views/main/index.njk
- src/server/views/payment/multiPaymentReceipt.njk
- src/server/views/payment/penaltyGroupTypeBreakdown.njk
- src/server/views/penalty/penaltyGroupSummary.njk
- test/controllers/payment.controller.spec.js
- test/data/penalties.js
- test/services/cpms.service.spec.js
- test/services/penalty.service.spec.js
* Ensure `BatchNumber` sent to CPMS orchestration is a string, not a number
* Replace `CASH` `PaymentMethod` with for postal/cheque
* Fix `chequeNumber` and `chequeDate` being inverted in CPMS transaction call
* Update copy for user testing
> Fix for non-card payment + reject search by reference for grouped penalty

- src/server/config.js
- src/server/controllers/payment.controller.js
- test/controllers/payment.controller.spec.js
* Usage of host header to generate redirect URL creates an internal URL
to the public portal containing an API prefix
* CPMS only whitelist the public URL, so they reject the transaction
* Add new envvar POST_PAYMENT_REDIRECT_BASE_URL to configure the base of
the public portal URL to return to
> Fix CPMS transaction creation failure in production

- src/server/views/reports/generatingReport.njk
* Report generation polling page was never reaching the download report
page in prod
* Base 64 content was returned due to missing binary media types
setting on API gateway
* Base 64 caused report status AJAX to fail due to incompatibility
with application/json Content-Type header
* Extra slash on status check success redirect URL caused 404
* Remove extra slash after baseUrl, as the baseUrl has a trailing slash
on dev/prod to reach the download page
> Fix report generation status checking failure

- src/server/app.js
* On dev/prod environments, TLS is terminated by API Gateway and proxied
to express which is serving standard HTTP
* Session cookie secure configuration prevented cookie being set,
meaning pages other than the start page had undefined user info
* Remove secure configuration to ensure cookie is set
> Fix issue where user info cookie was not being set in dev/prod envs

- src/server/views/penalty/vehicleRegSearchResults.njk
* Previously, we didn't allow operators to visit cancelled payment codes
due to API restrictions
* Now documents doesn't 404 for cancelled penalties we allow cancelled
penalties to be viewed
* Remove check for whether the code is cancelled when deciding whether
or not to show the payment code link
> Prevent hiding of link on search results for cancelled payment codes

- src/server/controllers/payment.controller.js
- src/server/services/cpms.service.js
- test/controllers/payment.controller.spec.js
- test/data/penaltyServiceGetResponses.js
- test/services/cpms.service.spec.js
* Ensure that we use `formattedReference` field from parsed single penalties, as opposed to `reference` field
> Fix unhyphenated IM references in CPMS transaction sales_reference

- src/server/config.js
- src/server/utils/httpclient.js
* Prepare for not making signed requests once API GW resource policies
are put in place over IAM authorisation
* Default to not making a signed request unless DO_SIGNED_REQUESTS=true
> Add feature flag around signing of HTTP requests

- src/server/controllers/main.controller.js
- test/controllers/main.controller.spec.js
- test/data/registrationSearch/registrationSearchResponses.js
* Assumptions were made that all penalty groups would contain at least
two penalties
* Now we have allowed for cancellation of partly paid penalty groups by
removing the unpaid part, we can have penalty groups consisting of a
single penalty
* Fix reg search code to accomodate this
> Fix issue search for vehicle reg in partial paid cancellation group

- src/server/middlewares/financeUsersAuthorization.middleware.js
- src/server/routes.js
- Splits the finance users authorizer into two: `reversePaymentAuthorizedRoles` and `reportsAuthorizedRoles`
- Allows `ContactCentre` role to access reports.
> adds contact centre staff to list of approved roles for reports

- src/server/controllers/payment.controller.js
- src/server/views/payment/penaltyGroupTypeBreakdown.njk
- src/server/views/penalty/penaltyDetails.njk
- test/controllers/payment.controller.spec.js
- test/data/penaltyServiceGetResponses.js
Remove the ability to take a cheque/postal order payment for immobilisations.
- Remove the radio buttons for payments/group payments
- Redirect on attempted invalid payment/group payment
> RSP-1654: Remove the ability to take a cheque/postal order payment for immobilisations

- src/public/scss/gds/variables/partials/_palette-colours.scss
- src/public/scss/styles.scss
- src/server/views/penalty/vehicleRegSearchResults.njk
Change the cancelled status colour to #f5a623 (orange) in the vehicle registration search view. The status is shown as 'UNPAID' or 'PAID' on the penalty details pages so has not been changed there.
> RSP-1547: Change cancelled status colour

- src/server/views/penalty/penaltyGroupSummary.njk
Fixed penalties and court deposit references were previously contained in a summary
Fixed penalties and court deposit references are now always visible
> RSP 1544: Move penalty details out of summary

- src/server/controllers/report.controller.js
- src/server/views/reports/generateReport.njk
On the generate report page, when the form is submitted without any radio buttons checked or with an invalid date range, the request would still be made to the CPMS orchestration service which would then respond with an error. The internal portal would then respond with `statusCode=500`.
- Set `required` on radio buttons
- Added validation to the generate report controller, redirecting to `reports?invalidDateRange` on rejection
- Added error messages in the same style as the home page (see screenshot)
> RSP-1679/RSP-1625: Generate report form validation

- src/public/scss/styles.scss
- src/server/views/layouts/partials/head.njk
- src/server/views/penalty/penaltyDetails.njk
- src/server/views/penalty/penaltyGroupSummary.njk
Replace `<a>` tag with `<input type="submit"... />`. Inline JS was blocked by the content security policy. Styled input as link so no visual changes have been made.
> RSP-1740: Remove inline JS from payment code cancellation

- src/public/js/dvsa/gds/modules/show-hide-content/index.js
Applied patch from latest version of DVSA front end:
https://github.com/dvsa/front-end/blob/2f051593b3a10274ec099344d052e6f88c7a4ac6/src/assets/js/shared/gds/modules/show-hide-content/index.js#L16
> Fix radio input selector for Safari

- .gitignore
- src/server/controllers/receipt.controller.js
- src/server/utils/dateTimeFormat.js
- src/server/views/payment/groupCash.njk
- src/server/views/payment/groupCheque.njk
- src/server/views/payment/groupPostalOrder.njk
- src/server/views/payment/multiPaymentReceipt.njk
- test/controllers/receipt.controller.spec.js
- Add CPMS reference
- Add missing create date/time
- Added create date/time to cash, cheque and postal order payment pages
> RSP-1623: Receipt code missing

- src/server/views/payment/cash.njk
- src/server/views/payment/cheque.njk
- src/server/views/payment/groupCash.njk
- src/server/views/payment/groupCheque.njk
- src/server/views/payment/groupPostalOrder.njk
- src/server/views/payment/multiPaymentReceipt.njk
- src/server/views/payment/postal.njk
- src/server/views/penalty/penaltyDetails.njk
- src/server/views/penalty/penaltyGroupSummary.njk
Since autoescape is disabled to be compatible with the DVSA front end (see https://github.com/dvsa/front-end/blob/v1.3.2/src/server/app.js#L36), escaping has been done manually for location which is the only string field allowing special characters (https://mozilla.github.io/nunjucks/templating.html#escape-aliased-as-e).
> RSP-1710: Input validation

- src/public/js/disable-button-on-click.js
- src/server/views/macros/elements/button.njk
- src/server/views/payment/cash.njk
- src/server/views/payment/cheque.njk
- src/server/views/payment/groupCash.njk
- src/server/views/payment/groupCheque.njk
- src/server/views/payment/groupPostalOrder.njk
- src/server/views/payment/postal.njk
Currently, if pay is double clicked, the payment is recorded in CPMS twice. Disable the pay button when clicked.
> RSP-1820: Disable double click on pay

- src/server/config.js
- src/server/controllers/paymentCode.controller.js
- src/server/controllers/penalty.controller.js
- src/server/services/penalty.service.js
- src/server/services/penaltyGroup.service.js
- src/server/utils/recentPayment.js
- src/server/views/penalty/penaltyDetails.njk
Block cancellation of penalties with recent payment attempts to stop internal portal users from cancelling payment codes with orphaned payments. Blocking cancellation for 1 hour from card payments being started.
> RSP-1747: Block cancellation of penalties with recent payment attempts

- .github/workflows/ci.yaml
- .gitignore
- New version of DVSA workflows will be available soon
- To avoid breaking current CI steps, pin to v1
- Add Mac file .DS_Store to .gitignore
Related issue: n/a
> feat: Version pin to v1 of DVSA GitHub actions

- src/server/app.js
- On Chrome, clicking the payment button which should direct users to the Capita payment page was redirecting back to the penalty page
- This was due to the Helmet upgrade which now default to: "form-action 'self'" whereas previously it allowed any.
- To fix, set `form-action: '*'` which allows any redirect and now allows redirecting to Capita payment page
Related issue: [RSP-2076](https://dvsa.atlassian.net/browse/RSP-2076)
> fix: Add fix for redirecting on capita page

- src/server/controllers/payment.controller.js
- src/server/controllers/paymentCode.controller.js
- src/server/controllers/penalty.controller.js
- src/server/services/payment.service.js
- src/server/utils/formatUserRole.js
- src/server/utils/httpclient.js
- src/server/utils/tryAddCancellationFlagToViewData.js
- src/server/views/penalty/penaltyDetails.njk
- src/server/views/penalty/penaltyGroupSummary.njk
- Fix missing param which caused error on deleting payments and penalties
- If the reverse card payment fails, the page reloads but no error message is shown
- Added new failed error type and returned to view penalty page for the user
- Fix for delete http client using `url` object instead of `href` string for request to payment service lambdas
Related issue: [RSP-2074](https://dvsa.atlassian.net/browse/RSP-2074)
> fix: Fix for delete failing and not displaying error

- .github/workflows/update-code.yaml
- Fix workflow job, removed `needs` attribute that pointed at non-existent jobs
Related issue: n/a
- [ x Have you performed a self-review of the code
> fix: Fix/upload workflow fix

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- Added tagging commands to tag when uploading to non-prod s3
- Added branches to ci.yaml to ignore tag creation
Related issue: [RSP-2115](https://dvsa.atlassian.net/browse/RSP-2115?atlOrigin=eyJpIjoiY2MxMDQ2NGY1MGFlNGNmYjgzNjBiNjlmMzAzMGQwZTkiLCJwIjoiaiJ9)
> feat: Add tagging into release workflow

- src/server/controllers/report.controller.js
- src/server/utils/logger.js
- src/server/utils/validDateRange.js
- src/server/validation/reports.js
- src/server/views/reports/generateReport.njk
- test/utils/validDateRange.spec.js
- Prevent user from generating reports with more than 28 days of data
- Added error catching for when CPMS rejects requests
- Added type logging for different types of validation failures
- Error message displayed to user is different based on failure
- Added reports.js to validation to store both types and messages
- Added new unit tests to check new 28 day validation, incorrect dates entered
Related issue: [RSP-2123](https://dvsa.atlassian.net/browse/RSP-2123?atlOrigin=eyJpIjoiM2IzNTFlODBiMzRjNGRiMGI4ZjU2NzJhMjRmMDc1ODMiLCJwIjoiaiJ9)
> feat: Add new 28 day validation and CPMS error catching

- dvsa-frontend-webpack/webpack.config.common.babel.js
- dvsa-frontend-webpack/webpack.config.development.babel.js
- dvsa-frontend-webpack/webpack.config.production.babel.js
- package.json
- Webpack was building in dev mode using eval
- CSP was blocking use of eval, which was breaking built pages
- To fix, updated webpack development build, remove old plugins, use webpack in-built source maps
- Removed duplicate packages from package.json
Related issue: n/a
> fix: Fix for local building issues

- src/server/controllers/payment.controller.js
- src/server/views/penalty/penaltyDetails.njk
- src/server/views/penalty/penaltyGroupSummary.njk
- Fixed an issue where no error message was displayed when an attempt to reverse a penalty on a single penalty had failed.
- Added context to error message, explaining it is not possible to reverse a payment within 24 hours of receipt - but not explicity stating this is why the payment failed.
Related issue: [RSP-2124](https://dvsa.atlassian.net/browse/RSP-2124?atlOrigin=eyJpIjoiOTBlMDFiMWFkYTNjNDBjMDlhOGY4MmE3YWMwZDE3ZGEiLCJwIjoiaiJ9)
> feat: Single penalty reversal failure error messages

- .snyk
- src/server/config.js
- src/server/services/penalty.service.js
- src/server/utils/isCancellable.js
- test/utils/isCancellable.spec.js
- Previously, there was no ability to cancel a single penalty - this functionality only existed on group payments.
- Added isCancellable property to penalty object to display cancel fine button.
- Created isCancellable util to contain logic to determine if a fine can be cancelled.
- Added unit tests covering isCancellable returning true or false, plus test with invalid data.
- Added default setting to orphanedPaymentCheckingTime config var.
Related issue: [RSP-1971](https://dvsa.atlassian.net/browse/RSP-1971?atlOrigin=eyJpIjoiZGVmNTk0MjM2ZTQ1NGFlZGJjMjVjODQyZTVmYjc1OWMiLCJwIjoiaiJ9)
> feat: added functionality for cancelling single payments, includes tests

- src/server/services/penalty.service.js
- src/server/utils/isReversible.js
- src/server/views/penalty/penaltyDetails.njk
- src/server/views/penalty/penaltyGroupSummary.njk
- test/utils/isCancellable.spec.js
- test/utils/isReversible.spec.js
- Previously, if a user tried to reverse a payment, the system would call to CPMS which would either approve or reject the request. When the request was rejected, an error message would be displayed explaining that it *may* be due to the timing, but this was not explicit. The aim for this ticket was to prevent a user from being able to attempt a reversal, if it was known CPMS would reject it due to the timing.
- A utility, isReversible.js, has been created which checks the payment status of a penalty, and the payment date, and determines whether it can be reversed. If a payment was made on the same day as the reversal attempt, the reversal will fail.
- Due to the way the group penalty service has been designed, it is very difficult to implement this functionality there. For now, changes …
> feat: added function to check if payments can be reversed

- src/server/services/penalty.service.js
- src/server/utils/isReversible.js
- src/server/views/penalty/penaltyDetails.njk
- test/utils/isReversible.spec.js
- When the reversible flow was introduced, there was no checking on the type of payments, despite the fact only card and cheque payments must wait until the next working day to reverse
- To fix, an if check has been added to the reversible utility, which checks if the payment type is CNP, CARD or CHEQUE
- paymentType is now passed in to the reversible function too to allow for checking
- Updated view to inform user that card or cheque payments cannot be reversed on the same day
- Added unit tests to cover each payment type being sent for reversal
Related issue: [RSP-2195](https://dvsa.atlassian.net/browse/RSP-2195?atlOrigin=eyJpIjoiOGIzODE2MjYwYzhiNDVkZjhmNmM3M2MzNzliZjc5N2QiLCJwIjoiaiJ9)
> fix: allow certain payment types to be reversed on the same day

- src/server/views/penalty/penaltyDetails.njk
Added a data-testid tag around the message which is is displayed when reverse a payment can not be done. This will help the playwright E2E test suite to select the element. 
Related issue: [RSP-2204](https://dvsa.atlassian.net/jira/software/c/projects/RSP/boards/830?modal=detail&selectedIssue=RSP-2204)
> feature: Added data-testid around unable to reverse payment message

- package-lock.json
- src/server/views/penalty/penaltyGroupSummary.njk
- There was an issue where a button was missing from the group penalty payment confirmation screen, which would've allowed the user to navigate back to the home page to pay more fines, if desired.
- This PR adds that button, improving accessibility and user experience.
Related issue: [RSP-2190](https://dvsa.atlassian.net/browse/RSP-2190?atlOrigin=eyJpIjoiM2ZmYWQzNTA1ZjY1NDhmZmI4MjZjYTc0OWQxY2MxOWEiLCJwIjoiaiJ9)
> feat: added Pay another penalty button to group payments

- src/server/controllers/paymentCode.controller.js
- src/server/controllers/penalty.controller.js
- Previously, in group penalties cancellation, a log would be made when the attempt was made, followed by a log with either a success or error.
- This diverges from single penalty cancellation, where a log is only made when the attempt succeeds or fails.
- Group payments have been updated to reflect this, logging out the userEmail, userRole and paymentCode, plus an error message in the case of an error.
- Single payment cancellation now also logs out userRole.
- Log titles have been updated to better reflect what they do (cancelPaymentCode -> cancelPenaltyGroup) and camel-casing has been properly applied.
Related issue: [RSP-2238](https://dvsa.atlassian.net/browse/RSP-2238)
> fix: Updated group payment logging

- src/server/config.js
- src/server/services/penalty.service.js
- src/server/services/penaltyGroup.service.js
- src/server/utils/isPaymentOverdue.js
- test/utils/isPaymentOverdue.spec.js
- New Feature Toggle environment variable
- If the feature toggle is true, the penalty is never marked as overdue so payment can be taken
- Updated `isPaymentOverdue` check to always return false if the feature toggle is set to true
- New unit tests to test feature toggle check
- Updated config to use variables from environment (process.env) instead of secrets manager
Related issue: [RSP-2242](https://dvsa.atlassian.net/browse/RSP-2242)
> feat: New env var to allow payment for overdue payments

- src/server/app.js
- The CSP was relaxed in an attempt to fix an issue with Imperva during release 4
- This is not required and should be restriced again
Related issue: [RSP-2237](https://dvsa.atlassian.net/browse/RSP-2237)
> feat: Restrict CSP for self and assets urls only

- .github/workflows/ci.yaml
- As part of the work for adding a lifecycle policy to RSP S3 bucket, a requirement surfaced for tagging objects uploaded to S3 based on their type (feat, fix, master).
- This incorporates the updated upload to s3 action.
- An optional tag is passed in, called lifecycle-subject, the value of which comes from an expression evaluating github refs
- It also became apparent that a previously existing check was not working, which should have prevented builds being uploaded to s3 if they did not start with feature or fix.
- This has been fixed, and expanded to include feat (shorthand for feature).
Related issue: [RSP-2091](https://dvsa.atlassian.net/browse/RSP-2091)
> ci: updated workflow to add new tags, fixed faulty if statement
