dvsa/rsp-internal-portal

src/server/config.js, src/server/controllers/cpms.controller.js, src/server/controllers/payment.controller.js, src/server/controllers/penalty.controller.js, src/server/routes.js, src/server/services/payment.service.js, src/server/services/penalty.service.js, src/server/views/cpms/cpms-step-1.njk, src/server/views/cpms/cpms-step-2.njk, src/server/views/cpms/cpms-step-3.njk, src/server/views/penalty/penaltyDetails.njk, test/services/penalty.service.spec.js, test/utils/mockedBackendAPI.js
Updates mocked CPMS screens to pass the correct data through
Updates penalty details page
Updates Unit tests
=> Adds real payment services

src/server/controllers/payment.controller.js, src/server/views/main/index.njk, src/server/views/payment/cash.njk, src/server/views/payment/cheque.njk, src/server/views/penalty/penaltyDetails.njk
Adds "Pay another penalty" button to the penalty details page
Fixes issue with payment code input maxlength
Fixes couple of minor issues on the cheque payment page
Adds check to prevent users from accessing the payment page when the penalty has already been paid
=> Adds cash payment page

src/server/controllers/main.controller.js, src/server/controllers/payment.controller.js
Fixes redirect when payment code is invalid
=> Fixes issue where payment code couldn't be entered with dashes

src/public/scss/styles.scss, src/server/controllers/main.controller.js, src/server/controllers/payment.controller.js, src/server/middlewares/authorization.middleware.js, src/server/routes.js, src/server/services/cpms.service.js, src/server/services/payment.service.js, src/server/services/penalty.service.js, src/server/views/macros/elements/button.njk, src/server/views/payment/failedPayment.njk, src/server/views/penalty/penaltyDetails.njk
Adds payment reversal functionality
Fixes couple of bugs
=> Reverse Payments

src/server/views/main/index.njk
* Hide reference search fields + move reg search to top and use as default
* Remove resend by email action on home page
=> RSP-1537: Disable reference search

package-lock.json, package.json, src/server/app.js, src/server/controllers/main.controller.js, src/server/controllers/payment.controller.js, src/server/controllers/paymentCode.controller.js, src/server/controllers/penalty.controller.js, src/server/controllers/receipt.controller.js, src/server/controllers/report.controller.js, src/server/middlewares/authorization.middleware.js, src/server/views/layouts/partials/header.njk
* Ammar's branch, I am approving + merging
* HTTP session was used to store session details server side
* This causes problems when running on Lambda, as the same Lambda can be hit by any user
* Use `cookie-session` to keep session details in a browser cookie
=> Fix session state storage being stored on serverside

src/server/controllers/payment.controller.js, src/server/middlewares/authorization.middleware.js, src/server/middlewares/financeUsersAuthorization.middleware.js
roles come in from AD like this -
```
'custom:Role': '[ContactCentre, FrontLine]',
```
Need to convert this to be an array of strings.
=> cleans up role string coming from AD before using it

src/server/config.js, src/server/controllers/payment.controller.js, src/server/middlewares/authorization.middleware.js, src/server/middlewares/financeUsersAuthorization.middleware.js, test/controllers/payment.controller.spec.js
* More permanently the better solution would be to either...
* Make the permitted roles configurable
* Or make dev AD setup the same as prod
* This just gets us going developing locally/on the dev env
=> Add feature flag around role checking

src/server/controllers/main.controller.js
Update the `rsp_refresh` cookie to have an expiry time of 4 hours.
=> RSP-1696: Session timeout

src/server/views/main/forbidden.njk, src/server/views/payment/cash.njk, src/server/views/payment/cheque.njk, src/server/views/payment/failedPayment.njk, src/server/views/payment/groupCash.njk, src/server/views/payment/groupCheque.njk, src/server/views/payment/groupPostalOrder.njk, src/server/views/payment/penaltyGroupTypeBreakdown.njk, src/server/views/payment/postal.njk, src/server/views/penalty/index.njk, src/server/views/penalty/penaltyDetails.njk, src/server/views/penalty/penaltyGroupSummary.njk, src/server/views/penalty/vehicleRegSearchResults.njk, src/server/views/reports/downloadReport.njk, src/server/views/reports/generateReport.njk, src/server/views/reports/generatingReport.njk
Jira ticket RSP-1542: "As an internal operator I only want to be able to navigate to the Home screen via the opt breadcrumb on each page"
Removed all breadcrumbs except home on all pages
=> RSP-1542: Only display home breadcrumb

src/public/js/generate-report.js, src/server/controllers/report.controller.js, src/server/utils/validDateRange.js, src/server/views/reports/generatingReport.njk, test/utils/validDateRange.spec.js
- Date range validation was broken due to broken logic (`dateToday <= dateFrom`): fixed and added unit test
- Moved out inline script which was blocked by the content security policy
=> Report generation fix

src/server/app.js
See https://helmetjs.github.io/docs/nocache/
=> RSP-1703: Disable caching

src/server/controllers/payment.controller.js
Previously removed with logging refactor.
=> Redirect on payment reversal

src/public/js/disable-button-on-click.js, src/server/controllers/payment.controller.js, src/server/views/payment/cash.njk, src/server/views/payment/cheque.njk, src/server/views/payment/groupCash.njk, src/server/views/payment/groupCheque.njk, src/server/views/payment/groupPostalOrder.njk, src/server/views/payment/postal.njk
Currently on older browsers, `<input type="number"... />` has no effect. Check validation on server side.
=> RSP-1834: Cash slip numeric validation

.eslintrc.json, dvsa-frontend-webpack/webpack.config.common.babel.js, package-lock.json, package.json, src/public/js/cookie-manager.js, src/public/js/dvsa/gds/modules/index.js, src/public/scss/modules/_modules.scss, src/public/scss/modules/cookie-banner/_cookie-banner.scss, src/public/scss/modules/cookie-details/_cookie-details.scss, src/public/scss/modules/cookie-preferences/_cookie-preferences.scss, src/server/controllers/cookieDetails.controller.js, src/server/controllers/cookiePreferences.controller.js, src/server/cookie-management/cookie-control.js, src/server/cookie-management/cookie-manager-config.js, src/server/routes.js, src/server/views/cookies/details.njk, src/server/views/cookies/index.njk, src/server/views/layouts/base.layout.njk, src/server/views/layouts/partials/body-scripts.njk, src/server/views/layouts/partials/cookie-banner.njk, src/server/views/layouts/partials/footer.njk, src/server/views/layouts/partials/head.njk
Implements cookie compliance based on www.gov.uk website
- Adds a cookie banner with options to accept all cookies or set preferences
- Adds a Cookie Preferences page allowing user to set their cookie preferences
- Adds a confirmation notification when the user updates their preferences on the Cookie Preferences page
- Adds a link in the footer to the Cookie Preferences page
=> Rsp 1888 cookie compliance

dvsa-frontend-webpack/webpack.config.common.babel.js, package-lock.json, package.json, src/public/js/cookie-manager.js, src/public/js/go-back.js, src/server/cookie-management/cookie-control.js, src/server/views/layouts/partials/body-scripts.njk, src/server/views/layouts/partials/head.njk
Implements fix for the back link in the cookie preferences confirmation notification.
JIRA: https://jira.dvsacloud.uk/browse/RSP-1888
- Adds an IIFE for the goBack functionality
- Adds a new bundle loaded in the body to ensure document has loaded
- Bumps app version
=> Rsp 1888 cookie compliance back link fix

src/server/app.js
Adds response headers for content type sniffing and xss.
=> rsp-1909-1913: Add response headers for xss and no sniff

.babelrc, package.json, serverless.yml
=> rsp-1917: upgrade node runtime

.github/workflows/ci.yaml, .github/workflows/update-code.yaml
- Using new DVSA workflow to update the Lambda code on AWS
- New workflow to be ran through the UI for updating the Lambda code
- Update CI.yaml to use latest version (v2.2) of DVSA workflows
Related issue: [RSP-2081](https://dvsa.atlassian.net/browse/RSP-2081)
=> feat: Add new workflow to update lambda function code

src/server/controllers/payment.controller.js
- Changed CARD to CNP in payment controller
Related issue: [RSP-2020](https://dvsa.atlassian.net/browse/RSP-2020?atlOrigin=eyJpIjoiMDBhNGY4MDdhM2QwNDdiOTllNGJmYjVhOGI5ZTEzOTIiLCJwIjoiaiJ9)
=> feat: Fix for correct logging of card payments on internal portal

src/server/controllers/payment.controller.js
- Added payment method type `POSTAL_ORDER` as both that and `POSTAL`
appear to be used in the db
- Group Payments using `POSTAL_ORDER`
- Moved misleading CPMS success log message when no call is made to CPMS
when payment type is Postal Order
- New logs when reversing a payment redirects due to payment method or
status UNPAID
Related issue: [RSP-2207](https://dvsa.atlassian.net/browse/RSP-2207)
=> fix: Payment Type Postal Order missing for reversing group payments

package-lock.json, package.json
- Cognito-Express version has been updated from 3.0.1, which includes an upgrade of jsonwebtoken to fix previously reported security vulnerabilites.
Related issue: [RSP-2193](https://dvsa.atlassian.net/browse/RSP-2193?atlOrigin=eyJpIjoiMzc5MWIxMzY5Y2NmNGE1MmI4Zjg4ODUzODEyODkzMjUiLCJwIjoiaiJ9)
=> build: updated cognito-express to 3.0.2

src/server/middlewares/authorization.middleware.js
- Add more info to error log to help with debugging user roles
Related issue: [RSP-2205](https://dvsa.atlassian.net/browse/RSP-2205)
=> fix: Add user role to error log for debugging

src/server/views/main/index.njk
new Validation,  input length match
Related issue: n/a
=> fix: amend input length on vehiclereg input
